### ISSUE TITLE
Folder structure not show

### ISSUE THREAD

**Issue by kilt-er** [leberechtreinhold/tts-cloud-manager#1]
The promise of this is amazing!  I just can't quite use it yet:

![TTSCloudManagerIssue](https://user-images.githubusercontent.com/71192938/93005083-64e9b900-f502-11ea-9d84-e6c705eead4d.JPG)

The folder structure is not shown.  As such, a folder cannot be selected, so I get an error message: "Please, select a single folder."  No folders are listed, either -- even subfolders in the TTS Cloud root directory.

Help!

**Comment by kilt-er** [comment]
I stripped out all the folder checks leaving the root folder as "" and got unblocked.  Would be nice to know why the folder structure is no longer being recognized and get a better fix.

**Comment by kilt-er** [comment]
Note, too, that once I put files into sub-folders from root, they did show up properly and were selectable, but it still seems that root cannot be selected, currently.

**Comment by leberechtreinhold** [comment]
Uhm, interesting, could you share the CloudInfo.bson so I can test it? It's on the folder of the program, with <Date>_CloudInfo.bson. That way I can load the same data and check.

I see the problem with the root at least: I have pushed a small commit that allows you to select the root, and It allowed me to select it and upload there. Do you mind trying?

**Comment by kilt-er** [comment]
Hey thanks for the fix!  Works great, appreciate having the root node.  The bson/json has all the links to my pre-release game content, so I'd rather not share that. 

Thanks again for the super helpful tool!
